{{- if .Values.extraCACerts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencode-rc.fullname" . }}-extra-ca-certs
  labels:
    {{- include "opencode-rc.labels" . | nindent 4 }}
data:
  ca-bundle.crt: |
    {{- .Values.extraCACerts | nindent 4 }}
{{- end }}
