{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencode-rc.secretName" . }}
  labels:
    {{- include "opencode-rc.labels" . | nindent 4 }}
type: Opaque
data:
  cookie-secret: {{ .Values.secrets.cookieSecret | b64enc }}
  oidc-client-secret: {{ .Values.secrets.oidcClientSecret | b64enc }}
{{- end }}
