{{- if ne .Values.profile "production" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencode-rc.fullname" . }}
  labels:
    {{- include "opencode-rc.labels" . | nindent 4 }}
type: Opaque
stringData:
  cookie-secret: {{ .Values.secrets.tokenSecret | default .Values.secrets.cookieSecret | quote }}
  oidc-client-secret: {{ .Values.secrets.oidcClientSecret | quote }}
  redis-url: {{ include "opencode-rc.redisUrl" . | quote }}
{{- end }}
