apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencode-rc.fullname" . }}-tunneler
  labels:
    {{- include "opencode-rc.labels" . | nindent 4 }}
    app.kubernetes.io/component: tunneler
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "opencode-rc.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: tunneler
